name: Release

on:
  push:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Check if there is any previous version 
        id: base_version
        run: |
          if grep "base" < version_info.txt; then
            echo "BASE_VERSION=true" >> "$GITHUB_OUTPUT"
            else
            echo "BASE_VERSION=false" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Set the base version as 3.0.0
        if: steps.base_version.outputs.BASE_VERSION == 'true'
        
        run: |
            git config --global user.email "aarya.hy@gmail.com"
            git config --global user.name "AruNiv"
            git tag -a v3.0.0 -m "my base version"
            gh release create v3.0.0            
            git push origin v3.0.0     
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
      
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: echo "Test_BaseVersion" | cat > version_info.txt
      - run: npm install --save-exact
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}

      - name: Push the changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'update the version'
          branch: main     
